version: '3.1'
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - "15432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always